[package]
name = "piston_playground"
version = "0.1.0"
authors = ["Henri Lunnikivi <henri.lunnikivi@gmail.com>"]

[[bin]]
name = "spinning-square"

[dependencies]
piston = "^0.27"
piston2d-graphics = "^0.19"
pistoncore-glutin_window = "^0.33"
piston2d-opengl_graphics = "^0.37"
specs = "*"
